<?php foreach ($block->getEntries() as $entry) : ?>
<div style="padding-left: <?php echo $entry['level'] * 20; ?>px;">
    <span class="entry-<?php echo $entry['type']; ?>">
        <?php echo $entry['alias']; ?> (<?php echo $entry['name']; ?>)
    </span>
    <?php if ($entry['extra']) : ?>
    (<?php echo $this->formatExtra($entry['extra']); ?>)
    <?php endif; ?>
    | <?php echo $entry['queryCount']; ?> queries
    <?php if (isset($entry['duration'])) : ?>
    | <span class="time <?php echo $this->colorInterval($entry['duration']); ?>"><?php echo number_format($entry['duration'], 2); ?>ms</span>
    <?php endif; ?>
    |
    <?php if ($entry['cached']) : ?>
    <span class="color-green">cached</span>
    <?php else : ?>
    <span class="color-red">not cached</span>
    <?php endif; ?>
</div>
<?php endforeach; ?>
